# Generated by Django 4.0.1 on 2022-01-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, default='', max_length=60)),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('Instructor', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, max_length=300)),
            ],
        ),
    ]
